---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by suxinwei.
--- DateTime: 2019/3/23 20:49
---
function main(splash, args)
    splash:go("http://www.baidu.com")
    splash:wait(0.5)
    local title = splash:evaljs("document.title")
    return { title = title }
end

-- Splash异步处理
function main(splash, args)
    local example_urls = { "www.baidu.com", "www.taobao.com", "www.zhihu.com" }
    local urls = args.urls or example_urls
    local results = {}
    for index, url in ipairs(urls) do
        local ok, reason = splash:go("http://" .. url)
        if ok then
            splash:wait(2)
            results[url] = splash:png()
        end
    end
    return results
end

--Splash API调用
function main(splash, args)
    local treat = require("treat")
    local response = splash:http_get("http://httpbin.org/get")
    return {
        html = treat.as_string(response.body),
        url = response.url,
        status = response.status
    }
end

--Splash_nginx
function main(splash, args)
    local treat = require("treat")
    local response = splash:http_get("http://httpbin.org/get")
    return treat.as_string(response.body)
end